name: EAS Build iOS

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install EAS CLI
        run: npm install -g eas-cli
      
      - name: Build iOS (Preview)
        run: eas build --platform ios --profile preview --non-interactive
